### ISSUE TITLE
Skin "AK-47 | Case Hardened" gets picked up as Weapon Case

### ISSUE THREAD

**Issue by psy0ch** [cantryDev/CSGOCaseStatsViewer#1]
A Case Hardened Trade gets picked up as a unboxing

```
AK-47 | Case Hardened (Minimal Wear)->? Huntsman Knife | Case Hardened (Well-Worn) (Yellow)
...
AK-47 | Case Hardened (Minimal Wear) Stats
? Huntsman Knife | Case Hardened (Well-Worn):1
...
Yellow
? Huntsman Knife | Case Hardened (Well-Worn) 
```

A check for the name Case Hardened should be set in place to mitigate this.
This wouldnt help if Valve ever were to release another Weaponskin called "...Case...", thought its unlikely.

**Comment by cantryDev** [comment]
Should be fixed now.
