### ISSUE TITLE
Java 1.8 or higher bug

### ISSUE THREAD

**Issue by CrabbbZ** [cantryDev/CSGOCaseStatsViewer#28]
C:\Users\----\Downloads>java -jar CSGOCaseStatsViewer-1.1.0-jar-with-dependencies.jar
'java' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\----\Downloads>echo off
'java' is not recognized as an internal or external command,
operable program or batch file.
You need Java 1.8 or higher to use this program
Press any key to continue . . .

Tried updating and uninstall-reinstalling java, restarted my pc but still doesnt work, any known fixes for this?

**Comment by jsayah** [comment]
Hey bud found the issue is the process in which it needs to run. You need to do option 1 first with your cookie data then 2 and 3 will work to analyze it!

**Comment by Rjpratt34** [comment]
Getting the same issue and no option to press 1 is coming up. Whenever I press any key nothing happens and after 3 attempts it auto closes.
