### ISSUE TITLE
Error: Unable to access jarfile CSGOCaseStatsViewer-1.1.0-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by Corvosh** [cantryDev/CSGOCaseStatsViewer#35]
Everytime i start the .bat data it wont work and shows me this message. 
<img width="670" alt="FEHLER CSGO" src="https://github.com/cantryDev/CSGOCaseStatsViewer/assets/133819670/ff7a768a-8169-4395-8456-ce4d2c9bc584">

Can someone pls help me?

**Comment by cantryDev** [comment]
Follow these Steps:
https://github.com/cantryDev/CSGOCaseStatsViewer#usage
