### ISSUE TITLE
It looks like you cloned...

### ISSUE THREAD

**Issue by nicoprod** [cantryDev/CSGOCaseStatsViewer#36]
C:\Windows\System32>java -jar CSGOCaseStatsViewer-1.1.0-jar-with-dependencies.jar
Error: Unable to access jarfile CSGOCaseStatsViewer-1.1.0-jar-with-dependencies.jar

C:\Windows\System32>echo off
It looks like you cloned the repository instead of downloading the newest release.
Download it from https://github.com/cantryDev/CSGOCaseStatsViewer/releases/latest
You will be redirected to the download page in 20 seconds

Thats my problem how can i fix it?

**Comment by cantryDev** [comment]
Follow these Steps:
https://github.com/cantryDev/CSGOCaseStatsViewer#usage
