### ISSUE TITLE
Cannot run the execute script

### ISSUE THREAD

**Issue by Mingsznee** [cantryDev/CSGOCaseStatsViewer#40]
Ran perfectly fine the first time before it crashed and restarting the executable didn't work either so I deleted the whole thing and reinstalled the zip folder and tried to run it again but it came out with this error. Tried both Chrome and Firefox but both spit out the same error.

**Comment by cantryDev** [comment]
Looks like you are not logged into steam when coping the cookies.
Site Note: Never share your cookies with anybody as they give access to your steam account.
