### ISSUE TITLE
Can't find JAR file!

### ISSUE THREAD

**Issue by LCDPWiLLiaM** [cantryDev/CSGOCaseStatsViewer#5]
I tried to run the .bat file, but in CMD it said: Error: Unable to access jarfile CSGOCaseStatsViewer-1.0.3-jar-with-dependencies.jar
How can I fix this?

**Comment by cantryDev** [comment]
You have to download the release and unzip the whole folder


https://github.com/cantryDev/CSGOCaseStatsViewer/releases/tag/1.0.3
![image](https://user-images.githubusercontent.com/16962714/107890649-558bf300-6f1a-11eb-85fe-d97b53d989f0.png)
