### ISSUE TITLE
help

### ISSUE THREAD

**Issue by kizercs** [cantryDev/CSGOCaseStatsViewer#6]
im new to this kind of thing so please dont be mad

when i try to run execute it says unable to access jarfile CSGOCaseStatsViewer-1.0.3-jar-with-dependencies.jar how do i fix thx in advance

**Comment by randomgamesman** [comment]
Shows the same thing for me, i tried updating java to no avail

**Comment by cantryDev** [comment]
Sounds like you downloaded the wrong file.

Go to https://github.com/cantryDev/CSGOCaseStatsViewer/releases/latest

![image](https://user-images.githubusercontent.com/16962714/118473940-d077cc00-b70a-11eb-9a1f-d1d0cdd59a62.png)

Download this file and try again.

Sorry for the late reply.
